name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

    - name: Verify formatting
      run: dart format lib --set-exit-if-changed

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web
